INSERT INTO PRODUCTS(ID, ITEM_CODE, DESCRIPTION, PRICE, STATE, CREATION_DATE, CREATOR_ID) VALUES (NEXTVAL('product_seq'), 142, 'mesa', 25.95, true, '2022-10-04', 1);
INSERT INTO PRODUCTS(ID, ITEM_CODE, DESCRIPTION, PRICE, STATE, CREATION_DATE, CREATOR_ID) VALUES (NEXTVAL('product_seq'), 724, 'silla', 13.50, true, '2022-10-04', 1);

INSERT INTO SUPPLIERS(ID, NAME, COUNTRY) VALUES (NEXTVAL('supplier_seq'), 'Pepe', 'Spain');
INSERT INTO SUPPLIERS(ID, NAME, COUNTRY) VALUES (NEXTVAL('supplier_seq'), 'Juan', 'Italy');

INSERT INTO SUPPLIERSPRODUCTS(SUPPLIERID, PRODUCTID) VALUES (1, 1);
INSERT INTO SUPPLIERSPRODUCTS(SUPPLIERID, PRODUCTID) VALUES (1, 2);
INSERT INTO SUPPLIERSPRODUCTS(SUPPLIERID, PRODUCTID) VALUES (2, 2);

INSERT INTO PRICEREDUCTIONS(ID, REDUCEDPRICE, STARTDATE, ENDDATE) VALUES (NEXTVAL('pricereductions_seq'), 0.3, '2022-10-03', '2022-10-07');
INSERT INTO PRICEREDUCTIONS(ID, REDUCEDPRICE, STARTDATE, ENDDATE) VALUES (NEXTVAL('pricereductions_seq'), 0.15, '2022-10-10', '2022-10-14');

INSERT INTO PRICEREDUCTIONSPRODUCTS(PRICEREDUCTIONID, PRODUCTID) VALUES (1, 1);
INSERT INTO PRICEREDUCTIONSPRODUCTS(PRICEREDUCTIONID, PRODUCTID) VALUES (2, 1);