CREATE TABLE IF NOT EXISTS PRODUCTS (
    ID INTEGER AUTO_INCREMENT,
    ITEMCODE INTEGER UNIQUE NOT NULL,
    DESCRIPTION VARCHAR,
    PRICE FLOAT,
    STATE BOOLEAN,
    CREATIONDATE DATE,
    CREATORID INTEGER NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS SUPPLIERS (
    ID INTEGER AUTO_INCREMENT,
    NAME VARCHAR NOT NULL,
    COUNTRY VARCHAR,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS SUPPLIERSPRODUCTS (
    SUPPLIERID INTEGER NOT NULL,
    PRODUCTID INTEGER NOT NULL,
    PRIMARY KEY (SUPPLIERID,PRODUCTID),
    CONSTRAINT FK_SupplierId_suppliersProducts FOREIGN KEY (SUPPLIERID) REFERENCES SUPPLIERS(ID),
    CONSTRAINT FK_ProductId_suppliersProducts FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS(ID)
);

CREATE TABLE IF NOT EXISTS PRICEREDUCTIONS (
    ID INTEGER AUTO_INCREMENT,
    REDUCEDPRICE FLOAT,
    STARTDATE DATE,
    ENDDATE DATE,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PRICEREDUCTIONSPRODUCTS (
    PRICEREDUCTIONID INTEGER NOT NULL,
    PRODUCTID INTEGER NOT NULL,
    PRIMARY KEY (PRICEREDUCTIONID,PRODUCTID),
    CONSTRAINT FK_PriceReductionId_priceReductionsProducts FOREIGN KEY (PRICEREDUCTIONID) REFERENCES PRICEREDUCTIONS(ID),
    CONSTRAINT FK_ProductId_priceReductionsProducts FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS(ID)
);