CREATE TABLE IF NOT EXISTS PRODUCTS (
    ID INTEGER AUTO_INCREMENT,
    ITEMCODE INTEGER UNIQUE NOT NULL,
    DESCRIPTION VARCHAR,
    PRICE FLOAT,
    STATE BOOLEAN,
    CREATIONDATE DATE,
    CREATORID INTEGER NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS REASON (
    ID INTEGER AUTO_INCREMENT,
    DESCRIPTION VARCHAR,
    CREATIONDATE DATE,
    PRODUCTID INTEGER NOT NULl,
    CONSTRAINT FK_ProductId_reason FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SUPPLIERS (
    ID INTEGER AUTO_INCREMENT,
    NAME VARCHAR NOT NULL,
    COUNTRY VARCHAR,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS SUPPLIERSPRODUCTS (
    SUPPLIERID INTEGER NOT NULL,
    PRODUCTID INTEGER NOT NULL,
    PRIMARY KEY (SUPPLIERID,PRODUCTID),
    CONSTRAINT FK_SupplierId_suppliersProducts FOREIGN KEY (SUPPLIERID) REFERENCES SUPPLIERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ProductId_suppliersProducts FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PRICEREDUCTIONS (
    ID INTEGER AUTO_INCREMENT,
    REDUCEDPRICE FLOAT,
    STARTDATE DATE,
    ENDDATE DATE,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PRICEREDUCTIONSPRODUCTS (
    PRICEREDUCTIONID INTEGER NOT NULL,
    PRODUCTID INTEGER NOT NULL,
    PRIMARY KEY (PRICEREDUCTIONID,PRODUCTID),
    CONSTRAINT FK_PriceReductionId_priceReductionsProducts FOREIGN KEY (PRICEREDUCTIONID) REFERENCES PRICEREDUCTIONS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ProductId_priceReductionsProducts FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS USERS (
    ID INTEGER AUTO_INCREMENT,
    USERNAME VARCHAR UNIQUE,
    PASSWORD VARCHAR,
    CREATIONDATE DATE,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ROLES (
    ID INTEGER AUTO_INCREMENT,
    ROLETYPE VARCHAR UNIQUE,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS USERROLES (
    USERID INTEGER NOT NULL,
    ROLEID INTEGER NOT NULL,
    PRIMARY KEY (USERID,ROLEID),
    CONSTRAINT FK_UserId_UserRoles FOREIGN KEY (USERID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_RoleId_UserRoles FOREIGN KEY (ROLEID) REFERENCES ROLES(ID) ON DELETE CASCADE
);